### ISSUE TITLE
Digging into apply() for strings

### ISSUE THREAD

**Issue by dlasusa** [mattharrison/effective_pandas_book#12]
I know we generally want to avoid apply(), especially for any numerical operations.  I just often find myself working with and parsing a variety of text (usually coming from csv, which in turn is coming from open textbox data, aka ugly).

Just wondering if Matt or anyone here knows of good resources to dig into using apply?  I can try to be more specific, but as an example, today I'm trying to run some sentiment analysis over 2 columns/series in a dataframe, and trying to turn that text into scores.  In this very specific case I'm using NRCLex and getting back a dict (like this: {'fear': 2, 'positive': 1, 'negative': 4, 'anticipation': 1}) Which I'm in turn trying creating columns based on that and the value is the dict value.  So for this record, column "fear" would have 2.

Anyway, not expecting a direct answer to this specific question (though that would be fine too!  ha!)  just more where I can look into the apply method and trying to learn how to better work with it. 

Thanks!

**Comment by mattharrison** [comment]
Hi @dlasusa 

Sometimes `.apply` is useful. When manipulating text, nested objects (like dictionaries), or even applying numpy functions (in that case it stays in the fast path).

A general rule of thumb is to think about how the data is stored. If it is numeric, you want to stay in the fast path by avoiding `.apply`. Dictionaries and strings aren't numeric and you kind of have to use Python to manipulate them. 🤷‍♀️

In your case, I'd be fine with `.apply`:

![image](https://user-images.githubusercontent.com/119405/161337895-8d8691df-6a5a-494b-be36-566afe6fc2ea.png)

**Comment by dlasusa** [comment]
Oh wow!  hadn't thought to try to use it quite like that.  Thanks!  I'll let ya know how it goes.

I almost feel bad asking about apply() since so often when I'M the one helping people with pandas I try to move them away from apply() (and iterrows).  Unless it's absolutely necessary.

**Comment by dlasusa** [comment]
This solution worked great @mattharrison Thanks!  

I wasn't sure how to get it to work in the context of a longer function.  I'm still working my way through your book, and not entirely clear when I should and shouldn't use lambda functions to work with the intermediate dataframes and values, so I usually end up almost always trying to use them (at least when assigning values). So I basically went csv --> main function (which returns a dataframe) --> Next function that basically does what you suggested.

Thanks again!  I learned a lot while working on this one.

**Comment by mattharrison** [comment]
Feel free to post code showing your concerns about lambda. I'll try to help
explain when to use them.

**Comment by dlasusa** [comment]
I appreciate that.

```py
import pandas as pd
import numpy as np
import datetime
from nrclex import NRCLex

def emotion_score(text_input):
    emotion = NRCLex(text_input)
    raw_scores = emotion.raw_emotion_scores
    return raw_scores

def process_reviews(input_df: pd.DataFrame):
    cols_to_drop = ['ReviewURL', 'Username', 'ID', 'RateText', 'Format', 'Thumbnails']
    return (input_df
        .drop(columns=cols_to_drop)
        .rename(columns={'Rate': 'rating'})
        [input_df.ProfileURL != 'https://www.amazon.comundefined']
        .assign(
            category='PR',
            product=1,
            helpful=lambda df_: df_.Helpful.str.partition(" ")[0].replace({"One": 1, np.nan: 0}).replace({",": ""}, regex=True).astype(int),
            hasMedia=lambda df_: ((df_["Images"].notnull()) | (df_["Video"].notnull())).astype(int),
            verified=lambda df_: df_["Verified"].notnull().astype(int),
            Title=lambda df_: df_.Title.astype(str),
            Content=lambda df_: df_.Content.astype(str),
            total_text=lambda df_: df_.Content + ' ' + df_.Title,
            date=lambda df_: pd.to_datetime(df_['Date'].str.split('on', expand=True)[1].str.strip(), format='%B %d, %Y'),
            title_scores=lambda df_: df_.Title.apply(emotion_score),
            content_scores=lambda df_: df_.Content.apply(emotion_score),
            total_scores=lambda df_: df_.total_text.apply(emotion_score)
        )
        .drop(columns=['Helpful', 'ProfileURL', 'Images', 'Video', 'Verified', 'Date', 'Title', 'Content', 'total_text', 'title_scores', 'content_scores']) # Drop these after we use them
    )

def tally_emotion_scores(input_df):
    return(input_df
            .assign(**input_df.total_scores.apply(pd.Series, dtype='object').fillna(0).astype('Int64'))
            .drop(columns=['total_scores'])
        )

ace_df1 = pd.read_csv('file.csv')
new_df = process_reviews(ace_df1)
new2_df = tally_emotion_scores(new_df)
new2_df # this get's written to a csv, but in a notebook, I'm just checking my output
```

Some of the code was for validation(some of the scores)....and isn't entirely necessary anymore, but it's still there for now.

**Comment by mattharrison** [comment]
First, I was playing around and you are probably better without apply.

![image](https://user-images.githubusercontent.com/119405/161388641-566ccffc-8fa0-41df-b273-9f877ae7407d.png)

**Comment by mattharrison** [comment]
On the "When to use `lambda` question"...

This is assuming column creation/update with `.assign`

- You have filtered/changed the dataframe prior to `.assign` . Particularly important if the index has changed
- You have created a new column (in the same `.assign` call and want access to it).

So for *total_text* above you want the use `lambda` because it is referencing title and content. (As an aside I'm not sure why title or content aren't strings and why you need those lines to convert them to strings but I can't see your data. Just wondering what other type they could be? 🤔)

For your first few columns, you don't technically need lambda, however were you to insert an operation that changed the index ahead in the chain, the lambda would be needed.

HTH!

**Comment by dlasusa** [comment]
Interesting.  I'll going to keep these as notes and sit with them a bit and keep referring back as I work through the book and exercises.  That said, what you just said helps a lot...especially being able to look at my code and see specific examples.  

If I were to create a new column in one `.assign` come out of that, filter some rows...and then create a new `.assign` does that mean I wouldn't have to use `lambda` since it's not in the same `.assign` ? (given I haven't changed other columns) 

Regarding your question about why I'm specifically setting the Title & Content to 'str' - honestly, I'm not entirely sure why I have to do that.  When I check the dtypes, they're "object" as you'd expect.  However, when sending them to NRCLex...I get a type error:
```
[TypeError: The `text` argument passed to `__init__(text)` must be a string, not <class 'float'>]()
```
So I figured I'd just make double sure it's a "str" and NRCLex stopped complaining.  (for better or worse? lol)
