### ISSUE TITLE
Setting values on the intermediate dataframe

### ISSUE THREAD

**Issue by dlasusa** [mattharrison/effective_pandas_book#16]
I have a df that is mostly a bunch of columns that contain numbers (dtypes are Int).  The index is a datetime type, but I don't think that's important for my question.  Here is my function:

```py
def tally_emotion_scores(input_df):
    pos_e = ['anticipation', 'surprise', 'joy', 'trust']
    neg_e = ['fear', 'anger', 'disgust', 'sadness']
    all_e = pos_e + neg_e
    return(input_df
            .assign(**pd.DataFrame(input_df.total_scores.to_list()).fillna(0).astype('Int64'))
            .drop(columns=['total_scores'])
            .assign(pos_neg_val= lambda df_: df_['positive'] - df_['negative'])
            .set_index('date')
            .sort_index()
        )
```

What I'd like to do is make changes to columns based on the `pos_neg_val`.

I can do it on the resulting df (`new2_df` is what's being returned from the function above).  So the following is what I want to do and it works, I'm just trying to figure out how to get this into my function.

```py
new2_df.loc[new2_df['pos_neg_val'] > 0, neg_e] = 0
new2_df.loc[new2_df['pos_neg_val'] <= 0, all_e] = 0
```

I thought I could use a lambda to access the intermediate df and tried several ways (trying to remember some):

When I tried (on the line right after assigning `pos_neg_val`):

```py
.loc[lambda df_: df_['pos_neg_val'] > 0, neg_e] = 0
```
I got:
`SyntaxError: cannot assign to subscript here. Maybe you meant '==' instead of '='?`

I think I tried adding another assign with versions of:

```py
.assign(
    pos_neg_val= lambda df_: df_['positive'] - df_['negative'],
    [[lambda df_: df_['pos_neg_val'] > 0, neg_e] = 0] # Try one
    [lambda df_: df_['pos_neg_val'] > 0, neg_e] = 0 # Try two
)
```
Neither of which looked right, but I tried anyway.

So I'm wondering how do I access and set the values on multiple columns based on a new created value on the intermediate df?

Thanks!

**Comment by akshatvishu** [comment]
I think the problem may with neg_e ; it should be either df_name['neg_e'] or used with quotation 'neg_e' while using .loc method

for more info on .loc checkout the documentation <https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html>

**Comment by mattharrison** [comment]
Hi @dlasusa 

This is hard to use your direct code because I don't have the data. However here is an attempt to get a minimal similar example with code/data that I have working:

```
# https://github.com/mattharrison/effective_pandas_book/issues/16#issuecomment-1156652777
import pandas as pd
autos = pd.read_csv('https://github.com/mattharrison/datasets/raw/master/data/vehicles.csv.zip',
                   usecols = ['barrels08', 'city08', 'comb08', 'highway08', 'cylinders', 'displ', 'drive', 'eng_dscr', 
        'fuelCost08', 'make', 'model', 'trany', 'range', 'createdOn', 'year']
)
pos_e = ['city08', 'barrels08']
neg_e = ['highway08', 'cylinders']

(autos
    # not sure how this works. I get a TypeError
    #.assign(**pd.DataFrame(autos.comb08.to_list()).fillna(0))
    # not the point of this question but this code works
    .assign(comb_08_total_scores=autos.comb08.fillna(0).astype('int16'))
    .drop(columns=['drive'])
    .assign(mpg_diff=lambda df:df.highway08 - df.city08,        
           )
    # make changes based on mpg_diff
    .pipe(lambda df: df.assign(**df[pos_e].where(df.mpg_diff > 6, 0)))
    .pipe(lambda df: df.assign(**df[neg_e].where(df.mpg_diff <= 6, 0))) 
)
```

In particular, you want to look at the `.pipe` calls.

**Comment by dlasusa** [comment]
Thanks to you both!  I appreciate you taking the time, plus given the fact I was unable to provide the data, which makes it extra difficult.  I think I really need to spend some to better under stand how `.pipe` works.  I'm still pretty/very fuzzy on it.
